/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
var google_api_servicecontrol_v1_check_error_pb = require('../../../../google/api/servicecontrol/v1/check_error_pb.js');
var google_api_servicecontrol_v1_operation_pb = require('../../../../google/api/servicecontrol/v1/operation_pb.js');
var google_rpc_status_pb = require('../../../../google/rpc/status_pb.js');
goog.exportSymbol('proto.google.api.servicecontrol.v1.CheckRequest', null, global);
goog.exportSymbol('proto.google.api.servicecontrol.v1.CheckResponse', null, global);
goog.exportSymbol('proto.google.api.servicecontrol.v1.ReportRequest', null, global);
goog.exportSymbol('proto.google.api.servicecontrol.v1.ReportResponse', null, global);
goog.exportSymbol('proto.google.api.servicecontrol.v1.ReportResponse.ReportError', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicecontrol.v1.CheckRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.api.servicecontrol.v1.CheckRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicecontrol.v1.CheckRequest.displayName = 'proto.google.api.servicecontrol.v1.CheckRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicecontrol.v1.CheckRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicecontrol.v1.CheckRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicecontrol.v1.CheckRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicecontrol.v1.CheckRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    serviceName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    operation: (f = msg.getOperation()) && google_api_servicecontrol_v1_operation_pb.Operation.toObject(includeInstance, f),
    serviceConfigId: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicecontrol.v1.CheckRequest}
 */
proto.google.api.servicecontrol.v1.CheckRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicecontrol.v1.CheckRequest;
  return proto.google.api.servicecontrol.v1.CheckRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicecontrol.v1.CheckRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicecontrol.v1.CheckRequest}
 */
proto.google.api.servicecontrol.v1.CheckRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setServiceName(value);
      break;
    case 2:
      var value = new google_api_servicecontrol_v1_operation_pb.Operation;
      reader.readMessage(value,google_api_servicecontrol_v1_operation_pb.Operation.deserializeBinaryFromReader);
      msg.setOperation(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setServiceConfigId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicecontrol.v1.CheckRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicecontrol.v1.CheckRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicecontrol.v1.CheckRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicecontrol.v1.CheckRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServiceName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOperation();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_api_servicecontrol_v1_operation_pb.Operation.serializeBinaryToWriter
    );
  }
  f = message.getServiceConfigId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string service_name = 1;
 * @return {string}
 */
proto.google.api.servicecontrol.v1.CheckRequest.prototype.getServiceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.api.servicecontrol.v1.CheckRequest.prototype.setServiceName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional Operation operation = 2;
 * @return {?proto.google.api.servicecontrol.v1.Operation}
 */
proto.google.api.servicecontrol.v1.CheckRequest.prototype.getOperation = function() {
  return /** @type{?proto.google.api.servicecontrol.v1.Operation} */ (
    jspb.Message.getWrapperField(this, google_api_servicecontrol_v1_operation_pb.Operation, 2));
};


/** @param {?proto.google.api.servicecontrol.v1.Operation|undefined} value */
proto.google.api.servicecontrol.v1.CheckRequest.prototype.setOperation = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.google.api.servicecontrol.v1.CheckRequest.prototype.clearOperation = function() {
  this.setOperation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.google.api.servicecontrol.v1.CheckRequest.prototype.hasOperation = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string service_config_id = 4;
 * @return {string}
 */
proto.google.api.servicecontrol.v1.CheckRequest.prototype.getServiceConfigId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.google.api.servicecontrol.v1.CheckRequest.prototype.setServiceConfigId = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicecontrol.v1.CheckResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.servicecontrol.v1.CheckResponse.repeatedFields_, null);
};
goog.inherits(proto.google.api.servicecontrol.v1.CheckResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicecontrol.v1.CheckResponse.displayName = 'proto.google.api.servicecontrol.v1.CheckResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.servicecontrol.v1.CheckResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicecontrol.v1.CheckResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicecontrol.v1.CheckResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicecontrol.v1.CheckResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicecontrol.v1.CheckResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    operationId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    checkErrorsList: jspb.Message.toObjectList(msg.getCheckErrorsList(),
    google_api_servicecontrol_v1_check_error_pb.CheckError.toObject, includeInstance),
    serviceConfigId: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicecontrol.v1.CheckResponse}
 */
proto.google.api.servicecontrol.v1.CheckResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicecontrol.v1.CheckResponse;
  return proto.google.api.servicecontrol.v1.CheckResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicecontrol.v1.CheckResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicecontrol.v1.CheckResponse}
 */
proto.google.api.servicecontrol.v1.CheckResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperationId(value);
      break;
    case 2:
      var value = new google_api_servicecontrol_v1_check_error_pb.CheckError;
      reader.readMessage(value,google_api_servicecontrol_v1_check_error_pb.CheckError.deserializeBinaryFromReader);
      msg.addCheckErrors(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setServiceConfigId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicecontrol.v1.CheckResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicecontrol.v1.CheckResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicecontrol.v1.CheckResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicecontrol.v1.CheckResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOperationId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCheckErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      google_api_servicecontrol_v1_check_error_pb.CheckError.serializeBinaryToWriter
    );
  }
  f = message.getServiceConfigId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string operation_id = 1;
 * @return {string}
 */
proto.google.api.servicecontrol.v1.CheckResponse.prototype.getOperationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.api.servicecontrol.v1.CheckResponse.prototype.setOperationId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated CheckError check_errors = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.google.api.servicecontrol.v1.CheckError>}
 */
proto.google.api.servicecontrol.v1.CheckResponse.prototype.getCheckErrorsList = function() {
  return /** @type{!Array.<!proto.google.api.servicecontrol.v1.CheckError>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_api_servicecontrol_v1_check_error_pb.CheckError, 2));
};


/** @param {!Array.<!proto.google.api.servicecontrol.v1.CheckError>} value */
proto.google.api.servicecontrol.v1.CheckResponse.prototype.setCheckErrorsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.api.servicecontrol.v1.CheckError=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.api.servicecontrol.v1.CheckError}
 */
proto.google.api.servicecontrol.v1.CheckResponse.prototype.addCheckErrors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.api.servicecontrol.v1.CheckError, opt_index);
};


proto.google.api.servicecontrol.v1.CheckResponse.prototype.clearCheckErrorsList = function() {
  this.setCheckErrorsList([]);
};


/**
 * optional string service_config_id = 5;
 * @return {string}
 */
proto.google.api.servicecontrol.v1.CheckResponse.prototype.getServiceConfigId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.google.api.servicecontrol.v1.CheckResponse.prototype.setServiceConfigId = function(value) {
  jspb.Message.setField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicecontrol.v1.ReportRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.servicecontrol.v1.ReportRequest.repeatedFields_, null);
};
goog.inherits(proto.google.api.servicecontrol.v1.ReportRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicecontrol.v1.ReportRequest.displayName = 'proto.google.api.servicecontrol.v1.ReportRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.servicecontrol.v1.ReportRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicecontrol.v1.ReportRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicecontrol.v1.ReportRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicecontrol.v1.ReportRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicecontrol.v1.ReportRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    serviceName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    operationsList: jspb.Message.toObjectList(msg.getOperationsList(),
    google_api_servicecontrol_v1_operation_pb.Operation.toObject, includeInstance),
    serviceConfigId: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicecontrol.v1.ReportRequest}
 */
proto.google.api.servicecontrol.v1.ReportRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicecontrol.v1.ReportRequest;
  return proto.google.api.servicecontrol.v1.ReportRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicecontrol.v1.ReportRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicecontrol.v1.ReportRequest}
 */
proto.google.api.servicecontrol.v1.ReportRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setServiceName(value);
      break;
    case 2:
      var value = new google_api_servicecontrol_v1_operation_pb.Operation;
      reader.readMessage(value,google_api_servicecontrol_v1_operation_pb.Operation.deserializeBinaryFromReader);
      msg.addOperations(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setServiceConfigId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicecontrol.v1.ReportRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicecontrol.v1.ReportRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicecontrol.v1.ReportRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicecontrol.v1.ReportRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServiceName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOperationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      google_api_servicecontrol_v1_operation_pb.Operation.serializeBinaryToWriter
    );
  }
  f = message.getServiceConfigId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string service_name = 1;
 * @return {string}
 */
proto.google.api.servicecontrol.v1.ReportRequest.prototype.getServiceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.api.servicecontrol.v1.ReportRequest.prototype.setServiceName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * repeated Operation operations = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.google.api.servicecontrol.v1.Operation>}
 */
proto.google.api.servicecontrol.v1.ReportRequest.prototype.getOperationsList = function() {
  return /** @type{!Array.<!proto.google.api.servicecontrol.v1.Operation>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_api_servicecontrol_v1_operation_pb.Operation, 2));
};


/** @param {!Array.<!proto.google.api.servicecontrol.v1.Operation>} value */
proto.google.api.servicecontrol.v1.ReportRequest.prototype.setOperationsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.api.servicecontrol.v1.Operation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.api.servicecontrol.v1.Operation}
 */
proto.google.api.servicecontrol.v1.ReportRequest.prototype.addOperations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.api.servicecontrol.v1.Operation, opt_index);
};


proto.google.api.servicecontrol.v1.ReportRequest.prototype.clearOperationsList = function() {
  this.setOperationsList([]);
};


/**
 * optional string service_config_id = 3;
 * @return {string}
 */
proto.google.api.servicecontrol.v1.ReportRequest.prototype.getServiceConfigId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.google.api.servicecontrol.v1.ReportRequest.prototype.setServiceConfigId = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicecontrol.v1.ReportResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.servicecontrol.v1.ReportResponse.repeatedFields_, null);
};
goog.inherits(proto.google.api.servicecontrol.v1.ReportResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicecontrol.v1.ReportResponse.displayName = 'proto.google.api.servicecontrol.v1.ReportResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.servicecontrol.v1.ReportResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicecontrol.v1.ReportResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicecontrol.v1.ReportResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicecontrol.v1.ReportResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicecontrol.v1.ReportResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    reportErrorsList: jspb.Message.toObjectList(msg.getReportErrorsList(),
    proto.google.api.servicecontrol.v1.ReportResponse.ReportError.toObject, includeInstance),
    serviceConfigId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicecontrol.v1.ReportResponse}
 */
proto.google.api.servicecontrol.v1.ReportResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicecontrol.v1.ReportResponse;
  return proto.google.api.servicecontrol.v1.ReportResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicecontrol.v1.ReportResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicecontrol.v1.ReportResponse}
 */
proto.google.api.servicecontrol.v1.ReportResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.api.servicecontrol.v1.ReportResponse.ReportError;
      reader.readMessage(value,proto.google.api.servicecontrol.v1.ReportResponse.ReportError.deserializeBinaryFromReader);
      msg.addReportErrors(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setServiceConfigId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicecontrol.v1.ReportResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicecontrol.v1.ReportResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicecontrol.v1.ReportResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicecontrol.v1.ReportResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReportErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.google.api.servicecontrol.v1.ReportResponse.ReportError.serializeBinaryToWriter
    );
  }
  f = message.getServiceConfigId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicecontrol.v1.ReportResponse.ReportError = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.api.servicecontrol.v1.ReportResponse.ReportError, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicecontrol.v1.ReportResponse.ReportError.displayName = 'proto.google.api.servicecontrol.v1.ReportResponse.ReportError';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicecontrol.v1.ReportResponse.ReportError.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicecontrol.v1.ReportResponse.ReportError.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicecontrol.v1.ReportResponse.ReportError} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicecontrol.v1.ReportResponse.ReportError.toObject = function(includeInstance, msg) {
  var f, obj = {
    operationId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    status: (f = msg.getStatus()) && google_rpc_status_pb.Status.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicecontrol.v1.ReportResponse.ReportError}
 */
proto.google.api.servicecontrol.v1.ReportResponse.ReportError.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicecontrol.v1.ReportResponse.ReportError;
  return proto.google.api.servicecontrol.v1.ReportResponse.ReportError.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicecontrol.v1.ReportResponse.ReportError} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicecontrol.v1.ReportResponse.ReportError}
 */
proto.google.api.servicecontrol.v1.ReportResponse.ReportError.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperationId(value);
      break;
    case 2:
      var value = new google_rpc_status_pb.Status;
      reader.readMessage(value,google_rpc_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicecontrol.v1.ReportResponse.ReportError.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicecontrol.v1.ReportResponse.ReportError.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicecontrol.v1.ReportResponse.ReportError} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicecontrol.v1.ReportResponse.ReportError.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOperationId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_rpc_status_pb.Status.serializeBinaryToWriter
    );
  }
};


/**
 * optional string operation_id = 1;
 * @return {string}
 */
proto.google.api.servicecontrol.v1.ReportResponse.ReportError.prototype.getOperationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.api.servicecontrol.v1.ReportResponse.ReportError.prototype.setOperationId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional google.rpc.Status status = 2;
 * @return {?proto.google.rpc.Status}
 */
proto.google.api.servicecontrol.v1.ReportResponse.ReportError.prototype.getStatus = function() {
  return /** @type{?proto.google.rpc.Status} */ (
    jspb.Message.getWrapperField(this, google_rpc_status_pb.Status, 2));
};


/** @param {?proto.google.rpc.Status|undefined} value */
proto.google.api.servicecontrol.v1.ReportResponse.ReportError.prototype.setStatus = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.google.api.servicecontrol.v1.ReportResponse.ReportError.prototype.clearStatus = function() {
  this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.google.api.servicecontrol.v1.ReportResponse.ReportError.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated ReportError report_errors = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.google.api.servicecontrol.v1.ReportResponse.ReportError>}
 */
proto.google.api.servicecontrol.v1.ReportResponse.prototype.getReportErrorsList = function() {
  return /** @type{!Array.<!proto.google.api.servicecontrol.v1.ReportResponse.ReportError>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.api.servicecontrol.v1.ReportResponse.ReportError, 1));
};


/** @param {!Array.<!proto.google.api.servicecontrol.v1.ReportResponse.ReportError>} value */
proto.google.api.servicecontrol.v1.ReportResponse.prototype.setReportErrorsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.api.servicecontrol.v1.ReportResponse.ReportError=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.api.servicecontrol.v1.ReportResponse.ReportError}
 */
proto.google.api.servicecontrol.v1.ReportResponse.prototype.addReportErrors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.api.servicecontrol.v1.ReportResponse.ReportError, opt_index);
};


proto.google.api.servicecontrol.v1.ReportResponse.prototype.clearReportErrorsList = function() {
  this.setReportErrorsList([]);
};


/**
 * optional string service_config_id = 2;
 * @return {string}
 */
proto.google.api.servicecontrol.v1.ReportResponse.prototype.getServiceConfigId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.google.api.servicecontrol.v1.ReportResponse.prototype.setServiceConfigId = function(value) {
  jspb.Message.setField(this, 2, value);
};


goog.object.extend(exports, proto.google.api.servicecontrol.v1);
