/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
var google_api_config_change_pb = require('../../../../google/api/config_change_pb.js');
var google_api_service_pb = require('../../../../google/api/service_pb.js');
var google_longrunning_operations_pb = require('../../../../google/longrunning/operations_pb.js');
var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js');
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var google_rpc_status_pb = require('../../../../google/rpc/status_pb.js');
goog.exportSymbol('proto.google.api.servicemanagement.v1.ChangeReport', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.ConfigFile', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.ConfigFile.FileType', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.ConfigRef', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.ConfigSource', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.Diagnostic', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.Diagnostic.Kind', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.ManagedService', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.OperationMetadata', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.OperationMetadata.Status', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.OperationMetadata.Step', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.Rollout', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.Rollout.RolloutStatus', null, global);
goog.exportSymbol('proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicemanagement.v1.ManagedService = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.api.servicemanagement.v1.ManagedService, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicemanagement.v1.ManagedService.displayName = 'proto.google.api.servicemanagement.v1.ManagedService';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.ManagedService.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicemanagement.v1.ManagedService.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicemanagement.v1.ManagedService} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.ManagedService.toObject = function(includeInstance, msg) {
  var f, obj = {
    serviceName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    producerProjectId: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicemanagement.v1.ManagedService}
 */
proto.google.api.servicemanagement.v1.ManagedService.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicemanagement.v1.ManagedService;
  return proto.google.api.servicemanagement.v1.ManagedService.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicemanagement.v1.ManagedService} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicemanagement.v1.ManagedService}
 */
proto.google.api.servicemanagement.v1.ManagedService.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setServiceName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setProducerProjectId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicemanagement.v1.ManagedService.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicemanagement.v1.ManagedService.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicemanagement.v1.ManagedService} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicemanagement.v1.ManagedService.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServiceName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getProducerProjectId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string service_name = 2;
 * @return {string}
 */
proto.google.api.servicemanagement.v1.ManagedService.prototype.getServiceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.google.api.servicemanagement.v1.ManagedService.prototype.setServiceName = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string producer_project_id = 3;
 * @return {string}
 */
proto.google.api.servicemanagement.v1.ManagedService.prototype.getProducerProjectId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.google.api.servicemanagement.v1.ManagedService.prototype.setProducerProjectId = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicemanagement.v1.OperationMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.servicemanagement.v1.OperationMetadata.repeatedFields_, null);
};
goog.inherits(proto.google.api.servicemanagement.v1.OperationMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicemanagement.v1.OperationMetadata.displayName = 'proto.google.api.servicemanagement.v1.OperationMetadata';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.servicemanagement.v1.OperationMetadata.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicemanagement.v1.OperationMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicemanagement.v1.OperationMetadata} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceNamesList: jspb.Message.getField(msg, 1),
    stepsList: jspb.Message.toObjectList(msg.getStepsList(),
    proto.google.api.servicemanagement.v1.OperationMetadata.Step.toObject, includeInstance),
    progressPercentage: jspb.Message.getFieldWithDefault(msg, 3, 0),
    startTime: (f = msg.getStartTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicemanagement.v1.OperationMetadata}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicemanagement.v1.OperationMetadata;
  return proto.google.api.servicemanagement.v1.OperationMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicemanagement.v1.OperationMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicemanagement.v1.OperationMetadata}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addResourceNames(value);
      break;
    case 2:
      var value = new proto.google.api.servicemanagement.v1.OperationMetadata.Step;
      reader.readMessage(value,proto.google.api.servicemanagement.v1.OperationMetadata.Step.deserializeBinaryFromReader);
      msg.addSteps(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProgressPercentage(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicemanagement.v1.OperationMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicemanagement.v1.OperationMetadata} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicemanagement.v1.OperationMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourceNamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getStepsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.google.api.servicemanagement.v1.OperationMetadata.Step.serializeBinaryToWriter
    );
  }
  f = message.getProgressPercentage();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getStartTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.Status = {
  STATUS_UNSPECIFIED: 0,
  DONE: 1,
  NOT_STARTED: 2,
  IN_PROGRESS: 3,
  FAILED: 4,
  CANCELLED: 5
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicemanagement.v1.OperationMetadata.Step = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.api.servicemanagement.v1.OperationMetadata.Step, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicemanagement.v1.OperationMetadata.Step.displayName = 'proto.google.api.servicemanagement.v1.OperationMetadata.Step';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.Step.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicemanagement.v1.OperationMetadata.Step.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicemanagement.v1.OperationMetadata.Step} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.Step.toObject = function(includeInstance, msg) {
  var f, obj = {
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    status: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicemanagement.v1.OperationMetadata.Step}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.Step.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicemanagement.v1.OperationMetadata.Step;
  return proto.google.api.servicemanagement.v1.OperationMetadata.Step.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicemanagement.v1.OperationMetadata.Step} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicemanagement.v1.OperationMetadata.Step}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.Step.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {!proto.google.api.servicemanagement.v1.OperationMetadata.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.Step.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicemanagement.v1.OperationMetadata.Step.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicemanagement.v1.OperationMetadata.Step} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicemanagement.v1.OperationMetadata.Step.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.Step.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.google.api.servicemanagement.v1.OperationMetadata.Step.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional Status status = 4;
 * @return {!proto.google.api.servicemanagement.v1.OperationMetadata.Status}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.Step.prototype.getStatus = function() {
  return /** @type {!proto.google.api.servicemanagement.v1.OperationMetadata.Status} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.google.api.servicemanagement.v1.OperationMetadata.Status} value */
proto.google.api.servicemanagement.v1.OperationMetadata.Step.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * repeated string resource_names = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.getResourceNamesList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 1));
};


/** @param {!Array.<string>} value */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.setResourceNamesList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.addResourceNames = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.google.api.servicemanagement.v1.OperationMetadata.prototype.clearResourceNamesList = function() {
  this.setResourceNamesList([]);
};


/**
 * repeated Step steps = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.google.api.servicemanagement.v1.OperationMetadata.Step>}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.getStepsList = function() {
  return /** @type{!Array.<!proto.google.api.servicemanagement.v1.OperationMetadata.Step>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.api.servicemanagement.v1.OperationMetadata.Step, 2));
};


/** @param {!Array.<!proto.google.api.servicemanagement.v1.OperationMetadata.Step>} value */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.setStepsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.api.servicemanagement.v1.OperationMetadata.Step=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.api.servicemanagement.v1.OperationMetadata.Step}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.addSteps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.api.servicemanagement.v1.OperationMetadata.Step, opt_index);
};


proto.google.api.servicemanagement.v1.OperationMetadata.prototype.clearStepsList = function() {
  this.setStepsList([]);
};


/**
 * optional int32 progress_percentage = 3;
 * @return {number}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.getProgressPercentage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.setProgressPercentage = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp start_time = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.getStartTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.setStartTime = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.google.api.servicemanagement.v1.OperationMetadata.prototype.clearStartTime = function() {
  this.setStartTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.google.api.servicemanagement.v1.OperationMetadata.prototype.hasStartTime = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicemanagement.v1.Diagnostic = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.api.servicemanagement.v1.Diagnostic, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicemanagement.v1.Diagnostic.displayName = 'proto.google.api.servicemanagement.v1.Diagnostic';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.Diagnostic.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicemanagement.v1.Diagnostic.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicemanagement.v1.Diagnostic} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.Diagnostic.toObject = function(includeInstance, msg) {
  var f, obj = {
    location: jspb.Message.getFieldWithDefault(msg, 1, ""),
    kind: jspb.Message.getFieldWithDefault(msg, 2, 0),
    message: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicemanagement.v1.Diagnostic}
 */
proto.google.api.servicemanagement.v1.Diagnostic.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicemanagement.v1.Diagnostic;
  return proto.google.api.servicemanagement.v1.Diagnostic.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicemanagement.v1.Diagnostic} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicemanagement.v1.Diagnostic}
 */
proto.google.api.servicemanagement.v1.Diagnostic.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocation(value);
      break;
    case 2:
      var value = /** @type {!proto.google.api.servicemanagement.v1.Diagnostic.Kind} */ (reader.readEnum());
      msg.setKind(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicemanagement.v1.Diagnostic.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicemanagement.v1.Diagnostic.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicemanagement.v1.Diagnostic} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicemanagement.v1.Diagnostic.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLocation();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getKind();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.google.api.servicemanagement.v1.Diagnostic.Kind = {
  WARNING: 0,
  ERROR: 1
};

/**
 * optional string location = 1;
 * @return {string}
 */
proto.google.api.servicemanagement.v1.Diagnostic.prototype.getLocation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.api.servicemanagement.v1.Diagnostic.prototype.setLocation = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional Kind kind = 2;
 * @return {!proto.google.api.servicemanagement.v1.Diagnostic.Kind}
 */
proto.google.api.servicemanagement.v1.Diagnostic.prototype.getKind = function() {
  return /** @type {!proto.google.api.servicemanagement.v1.Diagnostic.Kind} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.google.api.servicemanagement.v1.Diagnostic.Kind} value */
proto.google.api.servicemanagement.v1.Diagnostic.prototype.setKind = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string message = 3;
 * @return {string}
 */
proto.google.api.servicemanagement.v1.Diagnostic.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.google.api.servicemanagement.v1.Diagnostic.prototype.setMessage = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicemanagement.v1.ConfigSource = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.servicemanagement.v1.ConfigSource.repeatedFields_, null);
};
goog.inherits(proto.google.api.servicemanagement.v1.ConfigSource, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicemanagement.v1.ConfigSource.displayName = 'proto.google.api.servicemanagement.v1.ConfigSource';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.servicemanagement.v1.ConfigSource.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.ConfigSource.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicemanagement.v1.ConfigSource.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicemanagement.v1.ConfigSource} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.ConfigSource.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 5, ""),
    filesList: jspb.Message.toObjectList(msg.getFilesList(),
    proto.google.api.servicemanagement.v1.ConfigFile.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicemanagement.v1.ConfigSource}
 */
proto.google.api.servicemanagement.v1.ConfigSource.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicemanagement.v1.ConfigSource;
  return proto.google.api.servicemanagement.v1.ConfigSource.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicemanagement.v1.ConfigSource} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicemanagement.v1.ConfigSource}
 */
proto.google.api.servicemanagement.v1.ConfigSource.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.google.api.servicemanagement.v1.ConfigFile;
      reader.readMessage(value,proto.google.api.servicemanagement.v1.ConfigFile.deserializeBinaryFromReader);
      msg.addFiles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicemanagement.v1.ConfigSource.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicemanagement.v1.ConfigSource.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicemanagement.v1.ConfigSource} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicemanagement.v1.ConfigSource.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getFilesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.google.api.servicemanagement.v1.ConfigFile.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 5;
 * @return {string}
 */
proto.google.api.servicemanagement.v1.ConfigSource.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.google.api.servicemanagement.v1.ConfigSource.prototype.setId = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * repeated ConfigFile files = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.google.api.servicemanagement.v1.ConfigFile>}
 */
proto.google.api.servicemanagement.v1.ConfigSource.prototype.getFilesList = function() {
  return /** @type{!Array.<!proto.google.api.servicemanagement.v1.ConfigFile>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.api.servicemanagement.v1.ConfigFile, 2));
};


/** @param {!Array.<!proto.google.api.servicemanagement.v1.ConfigFile>} value */
proto.google.api.servicemanagement.v1.ConfigSource.prototype.setFilesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.api.servicemanagement.v1.ConfigFile=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.api.servicemanagement.v1.ConfigFile}
 */
proto.google.api.servicemanagement.v1.ConfigSource.prototype.addFiles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.api.servicemanagement.v1.ConfigFile, opt_index);
};


proto.google.api.servicemanagement.v1.ConfigSource.prototype.clearFilesList = function() {
  this.setFilesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicemanagement.v1.ConfigFile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.api.servicemanagement.v1.ConfigFile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicemanagement.v1.ConfigFile.displayName = 'proto.google.api.servicemanagement.v1.ConfigFile';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.ConfigFile.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicemanagement.v1.ConfigFile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicemanagement.v1.ConfigFile} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.ConfigFile.toObject = function(includeInstance, msg) {
  var f, obj = {
    filePath: jspb.Message.getFieldWithDefault(msg, 1, ""),
    fileContents: msg.getFileContents_asB64(),
    fileType: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicemanagement.v1.ConfigFile}
 */
proto.google.api.servicemanagement.v1.ConfigFile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicemanagement.v1.ConfigFile;
  return proto.google.api.servicemanagement.v1.ConfigFile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicemanagement.v1.ConfigFile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicemanagement.v1.ConfigFile}
 */
proto.google.api.servicemanagement.v1.ConfigFile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilePath(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setFileContents(value);
      break;
    case 4:
      var value = /** @type {!proto.google.api.servicemanagement.v1.ConfigFile.FileType} */ (reader.readEnum());
      msg.setFileType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicemanagement.v1.ConfigFile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicemanagement.v1.ConfigFile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicemanagement.v1.ConfigFile} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicemanagement.v1.ConfigFile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilePath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFileContents_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getFileType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.google.api.servicemanagement.v1.ConfigFile.FileType = {
  FILE_TYPE_UNSPECIFIED: 0,
  SERVICE_CONFIG_YAML: 1,
  OPEN_API_JSON: 2,
  OPEN_API_YAML: 3,
  FILE_DESCRIPTOR_SET_PROTO: 4
};

/**
 * optional string file_path = 1;
 * @return {string}
 */
proto.google.api.servicemanagement.v1.ConfigFile.prototype.getFilePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.api.servicemanagement.v1.ConfigFile.prototype.setFilePath = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional bytes file_contents = 3;
 * @return {!(string|Uint8Array)}
 */
proto.google.api.servicemanagement.v1.ConfigFile.prototype.getFileContents = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes file_contents = 3;
 * This is a type-conversion wrapper around `getFileContents()`
 * @return {string}
 */
proto.google.api.servicemanagement.v1.ConfigFile.prototype.getFileContents_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getFileContents()));
};


/**
 * optional bytes file_contents = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getFileContents()`
 * @return {!Uint8Array}
 */
proto.google.api.servicemanagement.v1.ConfigFile.prototype.getFileContents_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getFileContents()));
};


/** @param {!(string|Uint8Array)} value */
proto.google.api.servicemanagement.v1.ConfigFile.prototype.setFileContents = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional FileType file_type = 4;
 * @return {!proto.google.api.servicemanagement.v1.ConfigFile.FileType}
 */
proto.google.api.servicemanagement.v1.ConfigFile.prototype.getFileType = function() {
  return /** @type {!proto.google.api.servicemanagement.v1.ConfigFile.FileType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.google.api.servicemanagement.v1.ConfigFile.FileType} value */
proto.google.api.servicemanagement.v1.ConfigFile.prototype.setFileType = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicemanagement.v1.ConfigRef = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.api.servicemanagement.v1.ConfigRef, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicemanagement.v1.ConfigRef.displayName = 'proto.google.api.servicemanagement.v1.ConfigRef';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.ConfigRef.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicemanagement.v1.ConfigRef.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicemanagement.v1.ConfigRef} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.ConfigRef.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicemanagement.v1.ConfigRef}
 */
proto.google.api.servicemanagement.v1.ConfigRef.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicemanagement.v1.ConfigRef;
  return proto.google.api.servicemanagement.v1.ConfigRef.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicemanagement.v1.ConfigRef} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicemanagement.v1.ConfigRef}
 */
proto.google.api.servicemanagement.v1.ConfigRef.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicemanagement.v1.ConfigRef.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicemanagement.v1.ConfigRef.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicemanagement.v1.ConfigRef} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicemanagement.v1.ConfigRef.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.api.servicemanagement.v1.ConfigRef.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.api.servicemanagement.v1.ConfigRef.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicemanagement.v1.ChangeReport = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.api.servicemanagement.v1.ChangeReport.repeatedFields_, null);
};
goog.inherits(proto.google.api.servicemanagement.v1.ChangeReport, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicemanagement.v1.ChangeReport.displayName = 'proto.google.api.servicemanagement.v1.ChangeReport';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.api.servicemanagement.v1.ChangeReport.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.ChangeReport.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicemanagement.v1.ChangeReport.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicemanagement.v1.ChangeReport} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.ChangeReport.toObject = function(includeInstance, msg) {
  var f, obj = {
    configChangesList: jspb.Message.toObjectList(msg.getConfigChangesList(),
    google_api_config_change_pb.ConfigChange.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicemanagement.v1.ChangeReport}
 */
proto.google.api.servicemanagement.v1.ChangeReport.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicemanagement.v1.ChangeReport;
  return proto.google.api.servicemanagement.v1.ChangeReport.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicemanagement.v1.ChangeReport} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicemanagement.v1.ChangeReport}
 */
proto.google.api.servicemanagement.v1.ChangeReport.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_api_config_change_pb.ConfigChange;
      reader.readMessage(value,google_api_config_change_pb.ConfigChange.deserializeBinaryFromReader);
      msg.addConfigChanges(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicemanagement.v1.ChangeReport.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicemanagement.v1.ChangeReport.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicemanagement.v1.ChangeReport} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicemanagement.v1.ChangeReport.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConfigChangesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      google_api_config_change_pb.ConfigChange.serializeBinaryToWriter
    );
  }
};


/**
 * repeated google.api.ConfigChange config_changes = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.google.api.ConfigChange>}
 */
proto.google.api.servicemanagement.v1.ChangeReport.prototype.getConfigChangesList = function() {
  return /** @type{!Array.<!proto.google.api.ConfigChange>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_api_config_change_pb.ConfigChange, 1));
};


/** @param {!Array.<!proto.google.api.ConfigChange>} value */
proto.google.api.servicemanagement.v1.ChangeReport.prototype.setConfigChangesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.api.ConfigChange=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.api.ConfigChange}
 */
proto.google.api.servicemanagement.v1.ChangeReport.prototype.addConfigChanges = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.api.ConfigChange, opt_index);
};


proto.google.api.servicemanagement.v1.ChangeReport.prototype.clearConfigChangesList = function() {
  this.setConfigChangesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicemanagement.v1.Rollout = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.api.servicemanagement.v1.Rollout.oneofGroups_);
};
goog.inherits(proto.google.api.servicemanagement.v1.Rollout, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicemanagement.v1.Rollout.displayName = 'proto.google.api.servicemanagement.v1.Rollout';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.api.servicemanagement.v1.Rollout.oneofGroups_ = [[5,200]];

/**
 * @enum {number}
 */
proto.google.api.servicemanagement.v1.Rollout.StrategyCase = {
  STRATEGY_NOT_SET: 0,
  TRAFFIC_PERCENT_STRATEGY: 5,
  DELETE_SERVICE_STRATEGY: 200
};

/**
 * @return {proto.google.api.servicemanagement.v1.Rollout.StrategyCase}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.getStrategyCase = function() {
  return /** @type {proto.google.api.servicemanagement.v1.Rollout.StrategyCase} */(jspb.Message.computeOneofCase(this, proto.google.api.servicemanagement.v1.Rollout.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicemanagement.v1.Rollout.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicemanagement.v1.Rollout} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.Rollout.toObject = function(includeInstance, msg) {
  var f, obj = {
    rolloutId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    createdBy: jspb.Message.getFieldWithDefault(msg, 3, ""),
    status: jspb.Message.getFieldWithDefault(msg, 4, 0),
    trafficPercentStrategy: (f = msg.getTrafficPercentStrategy()) && proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.toObject(includeInstance, f),
    deleteServiceStrategy: (f = msg.getDeleteServiceStrategy()) && proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.toObject(includeInstance, f),
    serviceName: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicemanagement.v1.Rollout}
 */
proto.google.api.servicemanagement.v1.Rollout.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicemanagement.v1.Rollout;
  return proto.google.api.servicemanagement.v1.Rollout.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicemanagement.v1.Rollout} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicemanagement.v1.Rollout}
 */
proto.google.api.servicemanagement.v1.Rollout.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRolloutId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedBy(value);
      break;
    case 4:
      var value = /** @type {!proto.google.api.servicemanagement.v1.Rollout.RolloutStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 5:
      var value = new proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy;
      reader.readMessage(value,proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.deserializeBinaryFromReader);
      msg.setTrafficPercentStrategy(value);
      break;
    case 200:
      var value = new proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy;
      reader.readMessage(value,proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.deserializeBinaryFromReader);
      msg.setDeleteServiceStrategy(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setServiceName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicemanagement.v1.Rollout.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicemanagement.v1.Rollout} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicemanagement.v1.Rollout.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRolloutId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCreatedBy();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getTrafficPercentStrategy();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.serializeBinaryToWriter
    );
  }
  f = message.getDeleteServiceStrategy();
  if (f != null) {
    writer.writeMessage(
      200,
      f,
      proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.serializeBinaryToWriter
    );
  }
  f = message.getServiceName();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.google.api.servicemanagement.v1.Rollout.RolloutStatus = {
  ROLLOUT_STATUS_UNSPECIFIED: 0,
  IN_PROGRESS: 1,
  SUCCESS: 2,
  CANCELLED: 3,
  FAILED: 4,
  PENDING: 5
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.displayName = 'proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.toObject = function(includeInstance, msg) {
  var f, obj = {
    percentagesMap: (f = msg.getPercentagesMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy}
 */
proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy;
  return proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy}
 */
proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getPercentagesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readDouble);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPercentagesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeDouble);
  }
};


/**
 * map<string, double> percentages = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,number>}
 */
proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.prototype.getPercentagesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,number>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      null));
};


proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy.prototype.clearPercentagesMap = function() {
  this.getPercentagesMap().clear();
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.displayName = 'proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.prototype.toObject = function(opt_includeInstance) {
  return proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy} msg The msg instance to transform.
 * @return {!Object}
 */
proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy}
 */
proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy;
  return proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy}
 */
proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * optional string rollout_id = 1;
 * @return {string}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.getRolloutId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.api.servicemanagement.v1.Rollout.prototype.setRolloutId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp create_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.google.api.servicemanagement.v1.Rollout.prototype.setCreateTime = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.google.api.servicemanagement.v1.Rollout.prototype.clearCreateTime = function() {
  this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string created_by = 3;
 * @return {string}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.getCreatedBy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.google.api.servicemanagement.v1.Rollout.prototype.setCreatedBy = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional RolloutStatus status = 4;
 * @return {!proto.google.api.servicemanagement.v1.Rollout.RolloutStatus}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.getStatus = function() {
  return /** @type {!proto.google.api.servicemanagement.v1.Rollout.RolloutStatus} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.google.api.servicemanagement.v1.Rollout.RolloutStatus} value */
proto.google.api.servicemanagement.v1.Rollout.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional TrafficPercentStrategy traffic_percent_strategy = 5;
 * @return {?proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.getTrafficPercentStrategy = function() {
  return /** @type{?proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy} */ (
    jspb.Message.getWrapperField(this, proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy, 5));
};


/** @param {?proto.google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy|undefined} value */
proto.google.api.servicemanagement.v1.Rollout.prototype.setTrafficPercentStrategy = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.google.api.servicemanagement.v1.Rollout.oneofGroups_[0], value);
};


proto.google.api.servicemanagement.v1.Rollout.prototype.clearTrafficPercentStrategy = function() {
  this.setTrafficPercentStrategy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.hasTrafficPercentStrategy = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional DeleteServiceStrategy delete_service_strategy = 200;
 * @return {?proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.getDeleteServiceStrategy = function() {
  return /** @type{?proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy} */ (
    jspb.Message.getWrapperField(this, proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy, 200));
};


/** @param {?proto.google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy|undefined} value */
proto.google.api.servicemanagement.v1.Rollout.prototype.setDeleteServiceStrategy = function(value) {
  jspb.Message.setOneofWrapperField(this, 200, proto.google.api.servicemanagement.v1.Rollout.oneofGroups_[0], value);
};


proto.google.api.servicemanagement.v1.Rollout.prototype.clearDeleteServiceStrategy = function() {
  this.setDeleteServiceStrategy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.hasDeleteServiceStrategy = function() {
  return jspb.Message.getField(this, 200) != null;
};


/**
 * optional string service_name = 8;
 * @return {string}
 */
proto.google.api.servicemanagement.v1.Rollout.prototype.getServiceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.google.api.servicemanagement.v1.Rollout.prototype.setServiceName = function(value) {
  jspb.Message.setField(this, 8, value);
};


goog.object.extend(exports, proto.google.api.servicemanagement.v1);
